[package]
authors = ["smartinez <smartinez@nuclearis.com>"]
edition = "2018"
name = "nuclearis"
version = "0.1.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp-std = { default-features = false, version = '2.0.0' }

